---

all:
  hosts:
    # NOTE: change "db_server_hostname" to match your server hostname
    has:
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_host: has
      
      # These variables are used by install roles
      oracle_release: 19c
      oracle_install_type: restart
      oracle_dir_base: /install
      #oracle_gi_media: LINUX.X64_193000_grid_home.zip
      oracle_gi_media: grid_home_2022_Oct.zip
  children:
    oracle:
      vars:
  vars:
