---

all:
  hosts:
    # NOTE: change "db_server_hostname" to match your server hostname
    oel10a-19-restart:
      address: 192.168.8.207
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_ssh_extra_args: ' -o StrictHostKeyChecking=no '
      ansible_host: oel10a-19-restart
      
      # These variables are used by install roles
      oracle_release: 19c
      oracle_install_type: restart
      oracle_url_base: http://kicklinux9/oracle/19c/
      oracle_db_ver_path: 23.0.0.0
      oracle_gi_image: grid_home_19_26.zip
      oracle_db_image: db_home_19_26.zip
  children:
    oracle:
      vars:
        oracle_db_ver_path: 19.26.0.0
  vars:
    scsi:
    - adapter:
        pciSlotNumber: 16
    - adapter:
        pciSlotNumber: 32
    disks:
    - disk: rootdg
      size: 10g
      bus: 0
    - disk: appdg
      size: 60g
      bus: 0
    cluster:
      oracle_cluster_name: restart23
      disks:
        - disk:
            size: 8G
            bus: 1
            count: 4

    network:
    - adapter:
      pciSlotNumber: 192
      network: "Public Network"
    - adapter:
      pciSlotNumber: 224
      network: "Barn Network"      
    ram: 32G
    cpu: 4

    vmware:
      vm_folder: VmFolder
      datastore: KINGSTON
    template: "OEL10 Template"
