all:
  hosts:
    rac19-b-node-1:
      address: 192.168.8.50
      oracle_crs_node_vip: rac19-b-lis-1
      oracle_release: 19c
      oracle_install_type: rac
    rac19-b-node-2:
      address: 192.168.8.51
      oracle_crs_node_vip: rac19-b-lis-2
      oracle_release: 19c
      oracle_install_type: rac
#    rac19-b-node-3:
#      address: 192.168.8.52
#      listener: rac19-b-lis-3
#      oracle_release: 19c
#      oracle_install_type: rac
  children:
    oracle:
      hosts:
        rac19-b-node-1:
        rac19-b-node-2:
#        rac19-b-node-3:
      vars:
        oracle_url_base: http://kicklinux/oracle/19c/
        oracle_gi_image: LINUX.X64_193000_grid_home.zip
  vars:
    scsi:
    - adapter:
        pciSlotNumber: 16
    - adapter:
        pciSlotNumber: 32
    disks:
    - disk: rootdg
      size: 10g
      bus: 0
    - disk: appdg
      size: 100g
      bus: 0
    network:
    - adapter:
      pciSlotNumber: 192
      network: "Public Network"
    - adapter:
      pciSlotNumber: 224
      network: "Barn Network"      
    ram: 16G
    cpu: 2

    vmware:
      vm_folder: VmFolder
      datastore: Kingston890G

    cluster:
      oracle_cluster_name: rac19c-b
      disks:
        - disk:
            size: 8G
            bus: 1
            count: 4
      addresses:
        rac19-b-lis-1: 192.168.8.53
        rac19-b-lis-2: 192.168.8.54
#        rac19-b-lis-3: 192.168.8.56
        rac19-b-scan: [192.168.8.57, 192.168.8.58, 192.168.8.59]

    oracle_crs_scan: rac19-b-scan
    oracle_password: Xb6a5ed2ff29f98d
    template: "RHEL9 Template"
