all:
  hosts:
    rhel9f-rac-b:
      address: 192.168.8.80
      oracle_crs_node_vip: rac26ai-b-vip-1
    rhel9g-rac-b:
      address: 192.168.8.81
      oracle_crs_node_vip: rac26ai-b-vip-2
  children:
    oracle:
      hosts:
        rhel9f-rac-b:
        rhel9g-rac-b:
      vars:
        oracle_release: 26ai
        oracle_install_type: rac

  vars:
    oracle_url_base: http://kicklinux9/oracle/26ai/
    scsi:
    - adapter:
        pciSlotNumber: 16
    - adapter:
        pciSlotNumber: 32
    disks:
    - disk: rootdg
      size: 10g
      bus: 0
    - disk: appdg
      size: 100g
      bus: 0
    network:
    - adapter:
      pciSlotNumber: 192
      network: "Public Network"
    - adapter:
      pciSlotNumber: 224
      network: "Barn Network"      
    ram: 16G
    cpu: 2

    vmware:
      vm_folder: VmFolder
      datastore: KINGSTON

    cluster:
      oracle_cluster_name: rac26ai-b
      disks:
        - disk:
            size: 8G
            bus: 1
            count: 4
      addresses:
        rac26ai-b-vip-1: 192.168.8.85
        rac26ai-b-vip-2: 192.168.8.86
        rac26ai-b-scan: [192.168.8.82, 192.168.8.83, 192.168.8.84]

    oracle_crs_scan: rac26ai-b-scan
    oracle_password: Xb6a5ed2ff29f98d
    template: "RHEL9Template"
