---

all:
  hosts:
    # NOTE: change "db_server_hostname" to match your server hostname
    rhel8c-19-restart:
      ansible_connection: ssh
      ansible_ssh_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_host: rhel8c-19-restart
      
      # These variables are used by install roles
      oracle_release: 19c
      oracle_install_type: restart
      oracle_url_base: http://kicklinux/oracle/19c/
      oracle_gi_image: LINUX.X64_193000_grid_home.zip
  children:
    oracle:
      vars:
  vars:
