---

all:
  hosts:
    # NOTE: change "db_server_hostname" to match your server hostname
    db_server_hostname:
      ansible_connection: ssh
      ansible_ssh_user: ec2-user
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/id_rsa.pem
      ansible_host: db_server_hostname
      
      # These variables are used by install roles
      oracle_release: 19c
      oracle_install_type: restart      
  children:
    oracle:
      vars:
  vars:
