---

# TODO: setcap cap_net_raw+ep  /usr/bin/ping (on Centos8)

- hosts: all
  collections:
    - ibre5041.ansible_oracle_modules    
  become: yes
  become_user: root
  become_method: sudo
  vars:
    password: AcrorA123456__
    oracle_db_ver_path: 23.26.1.0.0
    oracle_home: "{{ oracle_install_dir_prod }}/{{ oracle_db_ver_path }}"
    oracle_sid: "APAC1"

  any_errors_fatal: true

  roles:    
  - role: default_vars_only
    tags: [always,default_vars_only]

  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID:  "{{ oracle_sid }}"
    
  tasks:      
    - name: create database
      oracle_db:
        oracle_home: "{{ oracle_home }}"
        db_name: 'APAC'
        sid: 'APAC'
        db_unique_name: 'APAC_AT_APAC'
        sys_password: "{{ password }}"
        #
        flashback: true
        archivelog: true        
        db_options:
          JSERVER: false
          ORACLE_TEXT: false
          IMEDIA: false
          CWMLITE: false
          SPATIAL: false
          OMS: false
          APEX: false
          DV: false
        initparams:
          sga_target: 4G
          sga_max_size: 4G
        storage_type: ASM
        datafile_dest: +XDATA
        recoveryfile_dest: +XDATA
        state: "{{ oracle_db_state | default('present') }}"
        cdb: true
      tags: [oracledb]
      become_user: "{{ oracle_os_user }}"
      become: yes

    - name: Creates a pdb PAPAC
      oracle_pdb:
        mode: sysdba
        #
        pdb_name: "PAPAC"
        state: opened
        pdb_admin_username: admin
        pdb_admin_password: "{{ password }}"
        roles: [CONNECT, PDB_DBA]
      tags: [oracledb]
      become_user: "{{ oracle_os_user }}"
      become: true
