
alter session set container=PEMEA;

select GSMADMIN_INTERNAL.GETSHARDINGMODE from dual;

select GROUP_TYPE, GROUP_COL_NUM, SHARD_TYPE, SHARD_COL_NUM, DEF_VERSION
from LOCAL_CHUNK_TYPES
WHERE TABFAM_ID=(SELECT TABFAM_ID FROM  LOCAL_TABLE_FAMILY_SERVICES WHERE SERVICE_NAME='rw_service.orasdb.oradbcloud')
;

select SHARD_LEVEL, COL_NAME, COL_IDX_IN_KEY, EFF_TYPE , CHARACTER_SET
from LOCAL_CHUNK_COLUMNS
WHERE TABFAM_ID=(SELECT TABFAM_ID FROM  LOCAL_TABLE_FAMILY_SERVICES WHERE SERVICE_NAME='rw_service.orasdb.oradbcloud')

select CHUNK_NAME, SHARD_KEY_LOW, SHARD_KEY_HIGH, GROUP_KEY_LOW ,  GROUP_KEY_HIGH, PRIORITY,  STATE, INST_ID, CHUNK_ID, SHARD_NAME, CHUNK_UNIQUE_ID
from LOCAL_CHUNKS
WHERE TABFAM_ID=(SELECT TABFAM_ID FROM  LOCAL_TABLE_FAMILY_SERVICES WHERE SERVICE_NAME='rw_service.orasdb.oradbcloud' )
and SHARD_KEY_LOW is not NULL and SHARD_KEY_HIGH is not NULL and CHUNK_NAME is not NULL

